"""add_audit_log

Revision ID: 29eb1f6b691e
Revises: 
Create Date: 2026-03-06 15:01:57.672201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29eb1f6b691e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=True),
    sa.Column('entity_id', sa.String(length=128), nullable=True),
    sa.Column('details_json', sa.Text(), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_user_id'), ['user_id'], unique=False)

    op.create_table('chat_reactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('emoji', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id', 'user_id', 'emoji', name='uq_reaction')
    )
    with op.batch_alter_table('chat_reactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_reactions_message_id'), ['message_id'], unique=False)
        batch_op.create_index('ix_reaction_message', ['message_id'], unique=False)

    op.create_table('user_blocks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('blocker_id', sa.Integer(), nullable=False),
    sa.Column('blocked_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('blocker_id', 'blocked_id', name='uq_block')
    )
    with op.batch_alter_table('user_blocks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_blocks_blocked_id'), ['blocked_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_blocks_blocker_id'), ['blocker_id'], unique=False)

    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sticker', sa.String(length=64), nullable=True))

    # NOTE: sale_records unique constraint skipped — existing data has duplicates
    # The index may already exist; create only if missing
    try:
        with op.batch_alter_table('sale_records', schema=None) as batch_op:
            batch_op.create_index('ix_sale_item_time', ['item_id', 'time_sold'], unique=False)
    except Exception:
        pass

    try:
        with op.batch_alter_table('tracked_items', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_tracked_items_item_id'), ['item_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_tracked_items_user_id'), ['user_id'], unique=False)
    except Exception:
        pass

    try:
        with op.batch_alter_table('users', schema=None) as batch_op:
            batch_op.add_column(sa.Column('last_active_at', sa.DateTime(), nullable=True))
    except Exception:
        pass

    # Clean up old migration leftovers
    try:
        op.drop_table('_tracked_items_old')
    except Exception:
        pass

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_active_at')

    with op.batch_alter_table('tracked_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tracked_items_user_id'))
        batch_op.drop_index(batch_op.f('ix_tracked_items_item_id'))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('sale_records', schema=None) as batch_op:
        batch_op.drop_constraint('uq_sale_dedup', type_='unique')
        batch_op.drop_index('ix_sale_item_time')

    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_column('sticker')

    op.create_table('_tracked_items_old',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('item_id', sa.VARCHAR(length=128), nullable=False),
    sa.Column('name', sa.VARCHAR(length=256), nullable=False),
    sa.Column('category', sa.VARCHAR(length=128), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), server_default=sa.text('(NULL)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('_tracked_items_old', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tracked_items_item_id'), ['item_id'], unique=1)

    with op.batch_alter_table('user_blocks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_blocks_blocker_id'))
        batch_op.drop_index(batch_op.f('ix_user_blocks_blocked_id'))

    op.drop_table('user_blocks')
    with op.batch_alter_table('chat_reactions', schema=None) as batch_op:
        batch_op.drop_index('ix_reaction_message')
        batch_op.drop_index(batch_op.f('ix_chat_reactions_message_id'))

    op.drop_table('chat_reactions')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_log_action'))

    op.drop_table('audit_log')
    # ### end Alembic commands ###
